stages:
- test
- build
- release

python2:
  image: python:2.7
  stage: test
  script:
  - apt-get install python-gtk2
  - pip install tox
  - tox -e py27


python34:
  image: python:3.4
  stage: test
  script:
  - apt-get install python-gtk2
  - pip install tox
  - tox -e py34

python35:
  image: python:3.5
  stage: test
  script:
  - apt-get install python-gtk2
  - pip install tox
  - tox -e py35

python36:
  image: python:3.6
  stage: test
  script:
  - apt-get install python-gtk2
  - pip install tox
  - tox -e py36

pages:
  image: alpine
  stage: release
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - sphinx-build -b html docs/ _build/html/
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master