name: Update Gvsbuild
on:
  workflow_dispatch:
  schedule:
    # min hour dom month dow
    - cron:  '0 5 * * 3'
env:
  python_version: '3.13'
  file: '.github/workflows/full-build.yml'
  yaml_key: '.jobs.windows.env.gvsbuild_version'

permissions:
  contents: read

jobs:

  check-version:
    runs-on: ubuntu-24.04
    outputs:
      current_version: ${{ steps.current-version.outputs.current_version }}
      latest_version: ${{ steps.latest-version.outputs.latest_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            pypi.org:443
            github.com:443
            api.github.com:443
            *.githubusercontent.com:443
            ghcr.io
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ env.python_version }}
      - name: Get current version
        id: current-version
        run: echo "current_version=$(yq ${yaml_key} ${file})" >> "$GITHUB_OUTPUT"
      - name: Get latest version
        id: latest-version
        run: |
          pip install --constraint=.github/constraints.txt lastversion
          echo "latest_version=$(python -m lastversion gvsbuild)" >> "$GITHUB_OUTPUT"

  update-version:
    runs-on: ubuntu-24.04
    needs: [ check-version ]
    if: ${{ needs.check-version.outputs.current_version != needs.check-version.outputs.latest_version }}
    permissions:
      pull-requests: write
      contents: write
    env:
      CURRENT: ${{ needs.check-version.outputs.current_version }}
      LATEST: ${{ needs.check-version.outputs.latest_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            *.githubusercontent.com:443
            ghcr.io
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          persist-credentials: false
      - name: Update version
        run: sed -i "$(yq '${yaml_key} | line' "${file}")s/$CURRENT/$LATEST/" "${file}"
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        id: generate-token
        with:
          app-id: ${{ secrets.GAPHOR_UPDATER_APP_ID }}
          private-key: ${{ secrets.GAPHOR_UPDATER_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Bump Gvsbuild to version ${{ env.LATEST }}
          branch: gvsbuild-update
          delete-branch: true
          title: 'Bump Gvsbuild from ${{ env.CURRENT }} to ${{ env.LATEST }}'
          body: |
            This PR was automatically created to make the following update:
            - Update to Gvsbuild version ${{ env.LATEST }}
          labels: |
            skip-changelog
