name: Update Gvsbuild
on:
  workflow_dispatch:
  schedule:
    # min hour dom month dow
    - cron:  '0 5 * * 3'
env:
  python_version: '3.12'
  file: '.github/workflows/full-build.yml'
  yaml_key: '.jobs.windows.env.gvsbuild_version'

jobs:

  check-version:
    runs-on: ubuntu-22.04
    outputs:
      current_version: ${{ steps.current-version.outputs.current_version }}
      latest_version: ${{ steps.latest-version.outputs.latest_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: ${{ env.python_version }}
      - name: Get current version
        id: current-version
        run: echo "current_version=$(yq ${{ env.yaml_key }} ${{ env.file }})" >> "$GITHUB_OUTPUT"
      - name: Get latest version
        id: latest-version
        run: |
          pip install --constraint=.github/constraints.txt lastversion
          echo "latest_version=$(python -m lastversion gvsbuild)" >> "$GITHUB_OUTPUT"

  update-version:
    runs-on: ubuntu-22.04
    needs: [ check-version ]
    if: ${{ needs.check-version.outputs.current_version != needs.check-version.outputs.latest_version }}
    permissions:
      pull-requests: write
      contents: write
    env:
      CURRENT: ${{ needs.check-version.outputs.current_version }}
      LATEST: ${{ needs.check-version.outputs.latest_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Update version
        run: sed -i "$(yq '${{ env.yaml_key }} | line' "${{ env.file }}")s/$CURRENT/$LATEST/" "${{ env.file }}"
      - name: Configure Git
        run: |
          git config user.email "ci@gaphor.org"
          git config user.name "GitHub Actions"
      - name: Push changes to new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout $COMMIT_SHA
          git switch -c gvsbuild-updates-${{ github.run_id }}
          git checkout origin/main -- ${ROOT_DIR}/.github/workflows
          git add ${{ env.file }}
          git commit -m "Bump Gvsbuild to version $LATEST"
          git push origin gvsbuild-updates-${{ github.run_id }}
      - name: Create Pull Request
        run: |
          gh pr create -B main -H gvsbuild-updates-${{ github.run_id }} \
            --title 'Bump Gvsbuild from ${{ env.CURRENT }} to ${{ env.LATEST }}' \
            --body 'This PR updates the Gvsbuild version.'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
