name: Update Gvsbuild
on:
  workflow_dispatch:
  schedule:
    # min hour dom month dow
    - cron:  '0 5 * * 3'
env:
  python_version: '3.12'
  file: '.github/workflows/full-build.yml'
  yaml_key: '.jobs.windows.env.gvsbuild_version'

jobs:

  check-version:
    runs-on: ubuntu-22.04
    outputs:
      current_version: ${{ steps.current-version.outputs.current_version }}
      latest_version: ${{ steps.latest-version.outputs.latest_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: ${{ env.python_version }}
      - name: Get current version
        id: current-version
        run: echo "current_version=$(yq ${{ env.yaml_key }} ${{ env.file }})" >> "$GITHUB_OUTPUT"
      - name: Get latest version
        id: latest-version
        run: |
          pip install --constraint=.github/constraints.txt lastversion
          echo "latest_version=$(python -m lastversion gvsbuild)" >> "$GITHUB_OUTPUT"

  update-version:
    runs-on: ubuntu-22.04
    needs: [ check-version ]
    if: ${{ needs.check-version.outputs.current_version != needs.check-version.outputs.latest_version }}
    permissions:
      pull-requests: write
      contents: write
    env:
      CURRENT: ${{ needs.check-version.outputs.current_version }}
      LATEST: ${{ needs.check-version.outputs.latest_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          ref: main
      - name: Update version
        run: sed -i "$(yq '${{ env.yaml_key }} | line' "${{ env.file }}")s/$CURRENT/$LATEST/" "${{ env.file }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          token: ${{ secrets.PR_CREATOR }}
          commit-message: Bump Gvsbuild to version ${{ env.LATEST }}
          branch: gvsbuild-update
          delete-branch: true
          title: 'Bump Gvsbuild from ${{ env.CURRENT }} to ${{ env.LATEST }}'
          body: |
            This PR was automatically created to make the following update:
            - Update to Gvsbuild version ${{ env.LATEST }}
          labels: |
            skip-changelog
