name: Pre-commit updater
on:
  workflow_dispatch:
  schedule:
    # min hour dom month dow
    - cron:  '0 5 * * 3'
env:
  python_version: '3.14'

permissions:
  contents: read

jobs:

  updater:
    name: Update
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            pypi.org:443
            github.com:443
            api.github.com:443
            *.githubusercontent.com:443
            ghcr.io
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.python_version }}
      - name: Use Python Dependency Cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-precommit
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Update pre-commit hooks
        run: pre-commit autoupdate --freeze
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: generate-token
        with:
          app-id: ${{ secrets.GAPHOR_UPDATER_APP_ID }}
          private-key: ${{ secrets.GAPHOR_UPDATER_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update pre-commit hooks
          branch: pre-commit-update
          delete-branch: true
          title: 'Update pre-commit hooks'
          body: |
            This PR was automatically created to make the following update:
            - Update pre-commit hooks
          labels: |
            skip-changelog
