name: Pre-commit updater
on:
  workflow_dispatch:
  schedule:
    # min hour dom month dow
    - cron:  '0 5 * * 3'
env:
  python_version: '3.13'

permissions:
  contents: read

jobs:

  updater:
    name: Update
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            pypi.org:443
            github.com:443
            api.github.com:443
            *.githubusercontent.com:443
            ghcr.io
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: ${{ env.python_version }}
          cache: pip
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Update pre-commit hooks
        run: pre-commit autoupdate --freeze
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: generate-token
        with:
          app-id: ${{ secrets.GAPHOR_UPDATER_APP_ID }}
          private-key: ${{ secrets.GAPHOR_UPDATER_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update pre-commit hooks
          branch: pre-commit-update
          delete-branch: true
          title: 'Update pre-commit hooks'
          body: |
            This PR was automatically created to make the following update:
            - Update pre-commit hooks
          labels: |
            skip-changelog
